"""add_material_stock_and_pipe_norms

Revision ID: 0241b9e47f20
Revises: b7db1f57d883
Create Date: 2026-03-03 10:25:28.139166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0241b9e47f20'
down_revision: Union[str, Sequence[str], None] = 'b7db1f57d883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False, comment='Название материала (совпадает с MaterialReceipt)'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Единица измерения (кг, м, шт)'),
    sa.Column('current_quantity', sa.Float(), nullable=False, comment='Текущий остаток'),
    sa.Column('min_quantity', sa.Float(), nullable=False, comment='Минимальный порог (для алерта «заканчивается»)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_stock_material_name'), 'material_stock', ['material_name'], unique=True)
    op.create_table('pipe_norms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dn', sa.Integer(), nullable=False, comment='Номинальный диаметр'),
    sa.Column('pn', sa.Integer(), nullable=False, comment='Номинальное давление'),
    sa.Column('sn', sa.Integer(), nullable=False, comment='Номинальная жёсткость'),
    sa.Column('with_sand', sa.Boolean(), nullable=False, comment='С песком / без песка'),
    sa.Column('resin_liner_kg', sa.Float(), nullable=True, comment='Смола на Лайнер, кг'),
    sa.Column('resin_winder_kg', sa.Float(), nullable=True, comment='Смола на Виндер (стекло), кг'),
    sa.Column('resin_sand_kg', sa.Float(), nullable=True, comment='Смола на Песок, кг'),
    sa.Column('cobalt_kg', sa.Float(), nullable=True, comment='Октоат кобальта, кг'),
    sa.Column('peroxide_kg', sa.Float(), nullable=True, comment='Акперокс, кг'),
    sa.Column('polyester_gauze_m', sa.Float(), nullable=True, comment='Полиэфирная марля, м'),
    sa.Column('veil_m', sa.Float(), nullable=True, comment='Вуаль, м'),
    sa.Column('stitched_mat_kg', sa.Float(), nullable=True, comment='Сшитый материал, кг'),
    sa.Column('ud300_m', sa.Float(), nullable=True, comment='UD300, м'),
    sa.Column('fiberglass_2400tex_kg', sa.Float(), nullable=True, comment='Стекловолокно 2400tex, кг'),
    sa.Column('sand_kg', sa.Float(), nullable=True, comment='Песок, кг'),
    sa.Column('ud250_m', sa.Float(), nullable=True, comment='UD250, м'),
    sa.Column('sand_gauze_m', sa.Float(), nullable=True, comment='Марля для песка, м'),
    sa.Column('wall_thickness_min_mm', sa.Float(), nullable=True, comment='Толщина стенки мин, мм'),
    sa.Column('wall_thickness_max_mm', sa.Float(), nullable=True, comment='Толщина стенки макс, мм'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipe_norms')
    op.drop_index(op.f('ix_material_stock_material_name'), table_name='material_stock')
    op.drop_table('material_stock')
    # ### end Alembic commands ###
