"""Initial setup

Revision ID: 281147b1b277
Revises: 
Create Date: 2026-02-23 08:30:52.840195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281147b1b277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False, comment='Название сырья (Смола, Песок и т.д.)'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='Количество прихода'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Единица измерения (кг, м, шт)'),
    sa.Column('batch_number', sa.String(length=100), nullable=True, comment='Номер партии поставщика'),
    sa.Column('entered_by', sa.BigInteger(), nullable=False, comment='Telegram ID начальника смены'),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dn', sa.Integer(), nullable=False, comment='Номинальный диаметр (DN)'),
    sa.Column('pn', sa.Integer(), nullable=False, comment='Номинальное давление (PN)'),
    sa.Column('sn', sa.Integer(), nullable=False, comment='Номинальная жесткость (SN)'),
    sa.Column('length', sa.Float(), nullable=False, comment='Длина трубы, м'),
    sa.Column('with_sand', sa.Boolean(), nullable=False, comment='Тип: с песком / без'),
    sa.Column('sand_layers', sa.Integer(), nullable=False, comment='Количество слоев песка (0, 1 или 2)'),
    sa.Column('has_bell', sa.Boolean(), nullable=False, comment='Наличие раструба/ниппеля (True) или прямая труба (False)'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество труб'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='Telegram ID администратора'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'QC_ENGINEER', 'SHIFT_LEADER', 'DOSING_OPERATOR', 'LAB_TECHNICIAN', 'TECHNOLOGIST', 'OPERATOR', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('pipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='Уникальный серийный номер, генерируется ОТК'),
    sa.Column('status', sa.Enum('CREATED', 'LINER', 'LINER_DRYING', 'WINDER', 'WINDER_DRYING', 'WAITING_QC_APPROVAL', 'TURNING', 'EXTRACTION', 'QC_FINAL', 'ACCEPTED', 'REJECTED', name='pipestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipes_serial_number'), 'pipes', ['serial_number'], unique=True)
    op.create_index(op.f('ix_pipes_task_id'), 'pipes', ['task_id'], unique=False)
    op.create_table('chemistry_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipe_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('LINER', 'WINDER_FIBERGLASS', 'WINDER_SAND_1', 'WINDER_SAND_2', name='chemistrystage', native_enum=False), nullable=False, comment='Стадия/подстадия: liner, winder_fiberglass, winder_sand_1, winder_sand_2'),
    sa.Column('resin_kg', sa.Float(), nullable=True, comment='Фактический расход смолы, кг'),
    sa.Column('cobalt_kg', sa.Float(), nullable=True, comment='Октоат кобальта 12 %, кг'),
    sa.Column('peroxide_kg', sa.Float(), nullable=True, comment='Акперокс (пероксид), кг'),
    sa.Column('entered_by', sa.BigInteger(), nullable=False, comment='Telegram ID дозировщика'),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemistry_logs_pipe_id'), 'chemistry_logs', ['pipe_id'], unique=False)
    op.create_table('dry_material_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipe_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('LINER', 'WINDER', name='drymaterialstage', native_enum=False), nullable=False, comment='Стадия: liner или winder'),
    sa.Column('polyester_gauze_m', sa.Float(), nullable=True, comment='Полиэфирная марля, м (Лайнер)'),
    sa.Column('veil_m', sa.Float(), nullable=True, comment='Вуаль, м (Лайнер)'),
    sa.Column('stitched_mat_kg', sa.Float(), nullable=True, comment='Сшитый материал, кг (Лайнер)'),
    sa.Column('ud300_m', sa.Float(), nullable=True, comment='UD300, м (Лайнер)'),
    sa.Column('fiberglass_2400tex_kg', sa.Float(), nullable=True, comment='Стекловолокно 2400tex, кг (Виндер)'),
    sa.Column('sand_kg', sa.Float(), nullable=True, comment='Песок, кг (Виндер)'),
    sa.Column('ud250_m', sa.Float(), nullable=True, comment='UD250, м (Виндер)'),
    sa.Column('sand_gauze_m', sa.Float(), nullable=True, comment='Марля для песка, м (Виндер)'),
    sa.Column('entered_by', sa.BigInteger(), nullable=False, comment='Telegram ID технолога'),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dry_material_logs_pipe_id'), 'dry_material_logs', ['pipe_id'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipe_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Enum('GEL_TIME_LINER', 'GEL_TIME_WINDER', 'SAND_ABSORBENCY', name='labtesttype', native_enum=False), nullable=False, comment='Тип теста: gel_time_liner, gel_time_winder, sand_absorbency'),
    sa.Column('gel_time_seconds', sa.Integer(), nullable=True, comment='Фактическое время гелеобразования, сек'),
    sa.Column('absorbency_result', sa.Text(), nullable=True, comment='Результат теста впитываемости (текстовое описание)'),
    sa.Column('is_homogeneous', sa.Boolean(), nullable=True, comment='Однородность смеси: True/False'),
    sa.Column('entered_by', sa.BigInteger(), nullable=False, comment='Telegram ID лаборанта'),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_pipe_id'), 'lab_tests', ['pipe_id'], unique=False)
    op.create_table('production_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipe_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('LINER', 'LINER_DRYING', 'WINDER', 'WINDER_DRYING', 'TURNING', 'EXTRACTION', name='stagetype', native_enum=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='Время старта стадии'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Время остановки стадии'),
    sa.Column('started_by', sa.BigInteger(), nullable=True, comment='Telegram ID нач. смены (СТАРТ)'),
    sa.Column('stopped_by', sa.BigInteger(), nullable=True, comment='Telegram ID нач. смены (СТОП)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_stages_pipe_id'), 'production_stages', ['pipe_id'], unique=False)
    op.create_table('qc_passports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipe_id', sa.Integer(), nullable=False),
    sa.Column('sand_layer_1_mm', sa.Float(), nullable=True, comment='Толщина 1-го слоя песка, мм'),
    sa.Column('sand_layer_2_mm', sa.Float(), nullable=True, comment='Толщина 2-го слоя песка, мм'),
    sa.Column('turning_approved', sa.Boolean(), nullable=True, comment='Разрешение на токарку (True/False)'),
    sa.Column('turning_approved_by', sa.BigInteger(), nullable=True, comment='Telegram ID инженера ОТК, давшего разрешение'),
    sa.Column('turning_approved_at', sa.DateTime(timezone=True), nullable=True, comment='Дата/время разрешения'),
    sa.Column('pipe_circumference_mm', sa.Float(), nullable=True, comment='Длина окружности трубы, мм'),
    sa.Column('bell_circumference_mm', sa.Float(), nullable=True, comment='Длина окружности раструба, мм'),
    sa.Column('wall_thickness_mm', sa.Float(), nullable=True, comment='Толщина стенки, мм'),
    sa.Column('bell_wall_thickness_mm', sa.Float(), nullable=True, comment='Толщина стенки раструба, мм'),
    sa.Column('nipple_outer_diameter_mm', sa.Float(), nullable=True, comment='Наружный диаметр ниппеля, мм'),
    sa.Column('channel_diameter_1_mm', sa.Float(), nullable=True, comment='Диаметр канала 1, мм'),
    sa.Column('channel_diameter_2_mm', sa.Float(), nullable=True, comment='Диаметр канала 2, мм (если есть)'),
    sa.Column('channel_depth_mm', sa.Float(), nullable=True, comment='Глубина каналов, мм'),
    sa.Column('channel_width_mm', sa.Float(), nullable=True, comment='Ширина каналов, мм'),
    sa.Column('machined_length_mm', sa.Float(), nullable=True, comment='Длина обработанной части, мм'),
    sa.Column('geometry_entered_by', sa.BigInteger(), nullable=True, comment='Telegram ID инженера ОТК (геометрия)'),
    sa.Column('geometry_entered_at', sa.DateTime(timezone=True), nullable=True, comment='Дата/время ввода геометрии'),
    sa.Column('visual_inspection_notes', sa.Text(), nullable=True, comment='Замечания визуального контроля (дефекты)'),
    sa.Column('final_verdict', sa.Enum('PASSED', 'REJECTED', name='finalverdict', native_enum=False), nullable=True, comment='Финальный статус: passed / rejected'),
    sa.Column('verdict_by', sa.BigInteger(), nullable=True, comment='Telegram ID инженера ОТК (финал)'),
    sa.Column('verdict_at', sa.DateTime(timezone=True), nullable=True, comment='Дата/время финального решения'),
    sa.ForeignKeyConstraint(['pipe_id'], ['pipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_passports_pipe_id'), 'qc_passports', ['pipe_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_passports_pipe_id'), table_name='qc_passports')
    op.drop_table('qc_passports')
    op.drop_index(op.f('ix_production_stages_pipe_id'), table_name='production_stages')
    op.drop_table('production_stages')
    op.drop_index(op.f('ix_lab_tests_pipe_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_dry_material_logs_pipe_id'), table_name='dry_material_logs')
    op.drop_table('dry_material_logs')
    op.drop_index(op.f('ix_chemistry_logs_pipe_id'), table_name='chemistry_logs')
    op.drop_table('chemistry_logs')
    op.drop_index(op.f('ix_pipes_task_id'), table_name='pipes')
    op.drop_index(op.f('ix_pipes_serial_number'), table_name='pipes')
    op.drop_table('pipes')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('material_receipts')
    # ### end Alembic commands ###
