"""lab_test_rename_fields_add_resin_percent

Revision ID: c4aa2f0672e3
Revises: 5fc25d67606a
Create Date: 2026-02-24 14:43:28.009801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4aa2f0672e3'
down_revision: Union[str, Sequence[str], None] = '5fc25d67606a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Переименование колонок (сохраняем данные!)
    op.alter_column('lab_tests', 'gel_time_seconds', new_column_name='gel_time_minutes',
                     type_=sa.Float(), existing_type=sa.Integer(),
                     comment='Время гелеобразования, мин')
    op.alter_column('lab_tests', 'resin_temperature_c', new_column_name='exothermic_peak_c',
                     comment='Температура экзотермического пика, °C')
    # Новая колонка
    op.add_column('lab_tests', sa.Column('theoretical_resin_percent', sa.Float(), nullable=True, comment='Теор. % смолы в песке'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_tests', sa.Column('gel_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True, comment='Фактическое время гелеобразования, сек'))
    op.add_column('lab_tests', sa.Column('resin_temperature_c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Температура смолы, °C'))
    op.drop_column('lab_tests', 'theoretical_resin_percent')
    op.drop_column('lab_tests', 'exothermic_peak_c')
    op.drop_column('lab_tests', 'gel_time_minutes')
    # ### end Alembic commands ###
