"""add lab fields

Revision ID: f648cb449983
Revises: 281147b1b277
Create Date: 2026-02-24 10:08:39.277245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f648cb449983'
down_revision: Union[str, Sequence[str], None] = '281147b1b277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_tests', sa.Column('room_temperature_c', sa.Float(), nullable=True, comment='Температура в цеху, °C'))
    op.add_column('lab_tests', sa.Column('resin_temperature_c', sa.Float(), nullable=True, comment='Температура смолы, °C'))
    op.add_column('lab_tests', sa.Column('viscosity_mpa_s', sa.Float(), nullable=True, comment='Вязкость, мПа·с'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_tests', 'viscosity_mpa_s')
    op.drop_column('lab_tests', 'resin_temperature_c')
    op.drop_column('lab_tests', 'room_temperature_c')
    # ### end Alembic commands ###
